"""Fixtures for the Rust and WebAssembly decoder of `.gnc` products, and the data bundle of the codec web views.

* `write_rust_tables(path)`: the rANS frequency tables, their id and the float32 constants of the predictor as Rust
  source (native/gnc/src/tables.rs). The decoder carries no tables of its own.
* `write_fixtures(out_dir)`: small products of every multilevel coder, the models they need and the lattice the
  Python decoder returns, for bit-exact parity tests of the Rust decoder (native/gnc/tests).
* `write_web_bundle(out_dir, regions, bounds)`: products, rasters and the manifest the codec views of the web page
  read. This function defines that format; web/src/codec/bundle.ts documents it for the reader.
"""
from __future__ import annotations

import gzip
import hashlib
import struct
from pathlib import Path

import numpy as np

from geoneural.codecs import multilevel as ml
from geoneural.codecs import package, rans
from geoneural.codecs.predictor import MAGIC as MODEL_MAGIC
from geoneural.codecs.predictor import Predictor
from geoneural.common import HOME, PACKAGE

ROOT = PACKAGE.parent.parent
GNC_CRATE = ROOT / "native" / "gnc"
WEB_BUNDLE = ROOT / "web" / "public" / "bundle" / "codec"


# ---- rANS tables as Rust source -----------------------------------------------------------------------------

def _f32_bits(v: float) -> int:
    return int(np.array([v], np.float32).view(np.uint32)[0])


def rust_tables() -> str:
    """Rust source of the tables and constants; the table id is recomputed from the frequencies and checked."""
    freq = np.asarray(rans.FREQ, np.int32)
    stamp = bytes([rans.PROB_BITS, rans.BINS_PER_OCTAVE])
    table_id = hashlib.sha256(freq.astype("<i4").tobytes() + stamp).hexdigest()[:16]
    if table_id != rans.TABLE_ID:
        raise RuntimeError(f"table id {table_id} differs from rans.TABLE_ID {rans.TABLE_ID}")
    if freq.max() > 0xFFFF:
        raise RuntimeError("frequencies do not fit u16")

    def rows(a):
        return "\n".join("    [" + ", ".join(str(int(v)) for v in row) + "]," for row in a)

    tid = ", ".join(f"0x{b:02x}" for b in bytes.fromhex(table_id))
    return f"""// Generated by geoneural.codecs.fixtures.write_rust_tables from geoneural.codecs.rans and multilevel.
// Do not edit; regenerate when the tables change (the table id changes with them).

/// First 8 bytes of sha256(FREQ as little-endian i32, PROB_BITS, BINS_PER_OCTAVE), as written in every product.
pub const TABLE_ID: [u8; 8] = [{tid}];
pub const PROB_BITS: u32 = {rans.PROB_BITS};
pub const RANS_L: u64 = {rans.RANS_L};
pub const MAX_E: usize = {rans.MAX_E};
pub const TOKENS: usize = {rans.TOKENS};
pub const BINS: usize = {rans.BINS};
pub const BINS_PER_OCTAVE: u8 = {rans.BINS_PER_OCTAVE};

pub const LATTICE_M: f64 = {ml.LATTICE_M!r};
pub const S0: usize = {ml.S0};
pub const LEVELS: usize = {ml.LEVELS};
pub const FEATURES: usize = {ml.FEATURES};
/// float32(LATTICE_M)
pub const LATTICE_M_F32: f32 = f32::from_bits(0x{_f32_bits(ml.LATTICE_M):08x});
/// float32(log2(SCALE_MIN))
pub const LOG2_SCALE_MIN_F32: f32 = f32::from_bits(0x{_f32_bits(ml.LOG2_SCALE_MIN):08x});

/// Token frequencies per bin, each row summing to 2^PROB_BITS.
pub static FREQ: [[u16; TOKENS]; BINS] = [
{rows(freq)}
];

/// Cumulative frequencies per bin, TOKENS + 1 entries from 0 to 2^PROB_BITS.
pub static CDF: [[u16; TOKENS + 1]; BINS] = [
{rows(np.asarray(rans.CDF, np.int64))}
];
"""


def write_rust_tables(path: Path | None = None) -> Path:
    path = Path(path or GNC_CRATE / "src" / "tables.rs")
    path.write_text(rust_tables())
    return path


# ---- parity fixtures ----------------------------------------------------------------------------------------

def terrain(side: int, seed: int, base: float = 150.0, relief: float = 40.0) -> np.ndarray:
    """Smooth folds plus a random walk along rows: steep and flat parts, no symmetry for a decoder to hide in."""
    rng = np.random.default_rng(seed)
    y, x = np.mgrid[0:side, 0:side] / side
    z = base + relief * np.sin(3 * x + seed) * np.cos(2 * y) + np.cumsum(rng.normal(0, 0.3, (side, side)), 1)
    return z.astype(np.float32)


def random_model(seed: int = 7, widths=(12, 10), scale: float = 0.5) -> Predictor:
    """An untrained predictor large enough to reach every branch of hard-swish."""
    rng = np.random.default_rng(seed)
    dims = [ml.FEATURES, *widths, 2]
    layers = []
    for i, (a, b) in enumerate(zip(dims[:-1], dims[1:])):
        W = rng.normal(0, scale if i < 2 else 0.1, (b, a))
        layers.append((W, rng.normal(0, 0.2, b)))
    return Predictor(layers)


def model_v1(model: Predictor) -> bytes:
    """The same predictor in the first file version (no class fields); it hashes as its version 2 bytes."""
    dims = [model.layers[0][0].shape[1]] + [W.shape[0] for W, _ in model.layers]
    body = b"".join(W.astype("<f2").tobytes() + b.astype("<f2").tobytes() for W, b in model.layers)
    return MODEL_MAGIC + struct.pack("<H4H", 1, *dims) + bytes.fromhex(rans.TABLE_ID) + body


def lattice_of(decoded_m: np.ndarray) -> np.ndarray:
    """Lattice integers of a decoded field; the Python decoder returns float32 lattice values times LATTICE_M."""
    lat = np.rint(np.asarray(decoded_m, np.float64) / ml.LATTICE_M).astype(np.int64)
    if not np.array_equal(lat.astype(np.float64) * ml.LATTICE_M, decoded_m):
        raise RuntimeError("decoded field is not on the lattice")
    return lat


def lattice_sha256(lattice: np.ndarray) -> str:
    return hashlib.sha256(np.ascontiguousarray(lattice, "<i8").tobytes()).hexdigest()


def _zst(raw: bytes) -> bytes:
    import zstandard
    return zstandard.ZstdCompressor(level=19).compress(raw)


def _cases(trained: Path | None):
    """(name, field, bound, arms); an arm is (tag, coder, model, how) with how one of none, embedded, corpus,
    corpus-v1 (the shared model given as a version 1 file)."""
    rnd = random_model()
    order0, ctx = ("order0", "cubic-order0", None, "none"), ("ctx", "cubic-ctx", None, "none")

    def learned(how, tag="learned", model=rnd):
        return tag, "learned", model, how

    yield "ridges-65", terrain(65, 1), 0.05, [order0, ctx, learned("embedded"), learned("corpus", "learned-corpus"),
                                             learned("corpus-v1", "learned-v1")]
    yield "ridges-129", terrain(129, 2), 0.1, [order0, ctx, learned("embedded")]
    yield "ridges-257", terrain(257, 3, relief=80.0), 0.25, [order0, ctx, learned("corpus")]
    # Near 3000 m with a 40 m cliff and heights 0.4 lattice units off the grid.
    alpine = terrain(129, 4, base=2940.0, relief=45.0)
    alpine[:, 70:] += np.float32(40.0)
    alpine += np.float32(0.0004)
    yield "alpine-129", alpine, 0.1, [order0, ctx, learned("corpus")]
    yield "pit-65", terrain(65, 5, base=-120.0, relief=200.0), 0.02, [ctx, learned("corpus")]
    noisy = terrain(129, 6) + np.random.default_rng(6).normal(0, 0.05, (129, 129)).astype(np.float32)
    yield "lossless-129", noisy, 0.0005, [order0, ctx, learned("corpus")]
    yield "tiny-9", terrain(9, 7), 0.01, [ctx, learned("embedded")]
    yield "tiny-3", terrain(3, 8), 0.01, [order0, learned("corpus")]
    ref = HOME / "atlases" / "essen-ruhr" / "reference.npy"
    if ref.exists():
        arms = [order0, ctx, learned("corpus")]
        if trained is not None:
            arms.append(learned("corpus", "trained", Predictor.from_bytes(trained.read_bytes())))
        yield "essen-257", np.load(ref)[384:641, 512:769], 0.1, arms


def write_fixtures(out_dir: Path | None = None, trained: Path | None = None, full_bound: float | None = 0.5,
                   log=print) -> Path:
    """Products, models and expected lattices for the Rust parity tests.

    cases.tsv: name, product, model (or -), rows, cols, coder, E, lattice (zstd of little-endian i64, or - when only
    its hash is kept), sha256 of the lattice as little-endian i64, sha256 of the decoded metres as little-endian f64.
    errors.tsv: name, product, model (or -), a substring of the error the decoder must raise. With a trained model,
    the whole 1025 x 1025 Essen field at `full_bound` is added, its lattice kept as a hash only.
    """
    out = Path(out_dir or GNC_CRATE / "tests" / "fixtures")
    out.mkdir(parents=True, exist_ok=True)
    for old in [*out.glob("*.gnc"), *out.glob("*.gnm"), *out.glob("*.zst")]:
        old.unlink()
    if trained is None:
        default = HOME / "results" / "v2" / "codec" / "models" / "loro-essen-ruhr-s0.gnm"
        trained = default if default.exists() else None

    def model_file(model: Predictor, version: str) -> str:
        name = f"model-{model.sha256()[:12]}-{version}.gnm"
        if not (out / name).exists():
            (out / name).write_bytes(model_v1(model) if version == "v1" else model.to_bytes())
        return name

    def one(name, z, bound, coder, model, how, keep_lattice=True):
        blob, recon, info = package.encode(z, bound, coder, model, embed_model=how == "embedded")
        given = model if how.startswith("corpus") else None
        if how == "corpus-v1":
            given = Predictor.from_bytes(model_v1(model))
        dec = package.decode(blob, given)
        if not np.array_equal(dec, recon):
            raise RuntimeError(f"{name}: Python decode differs from the encoder's reconstruction")
        lat = lattice_of(dec)
        (out / f"{name}.gnc").write_bytes(blob)
        lat_file = "-"
        if keep_lattice:
            # Fixed coders share their reconstruction (only the tables differ), so lattices are stored by content.
            lat_file = f"lattice-{lattice_sha256(lat)[:12]}.i64.zst"
            if not (out / lat_file).exists():
                (out / lat_file).write_bytes(_zst(np.ascontiguousarray(lat, "<i8").tobytes()))
        mfile = model_file(model, "v1" if how == "corpus-v1" else "v2") if how.startswith("corpus") else "-"
        heights = hashlib.sha256(np.ascontiguousarray(dec, "<f8").tobytes()).hexdigest()
        return [name, f"{name}.gnc", mfile, str(z.shape[0]), str(z.shape[1]), coder, str(info["E"]), lat_file,
                lattice_sha256(lat), heights]

    rows = []
    for field_name, z, bound, arms in _cases(trained):
        for tag, coder, model, how in arms:
            rows.append(one(f"{field_name}-{tag}", z, bound, coder, model, how))
            log(f"{rows[-1][0]}: {len((out / rows[-1][1]).read_bytes())} bytes")
    ref = HOME / "atlases" / "essen-ruhr" / "reference.npy"
    if trained is not None and full_bound is not None and ref.exists():
        z = np.load(ref)
        rows.append(one(f"essen-1025-trained-{full_bound:g}", z, full_bound, "learned",
                        Predictor.from_bytes(trained.read_bytes()), "corpus", keep_lattice=False))
        log(f"{rows[-1][0]}: {len((out / rows[-1][1]).read_bytes())} bytes")
    (out / "cases.tsv").write_text("".join("\t".join(r) + "\n" for r in rows))

    # Products the decoder must refuse: a bound-allocation rule and a geology context it does not implement.
    errors = []
    z = terrain(65, 9)
    blob, _, _ = package.encode(z, 0.25, "cubic-ctx", rule={"kind": "slope", "slopeRef": 0.02, "gamma": 1.0,
                                                           "factor": 0.25, "fromStride": 8})
    (out / "refuse-rule.gnc").write_bytes(blob)
    errors.append(["refuse-rule", "refuse-rule.gnc", "-", "rule"])
    geo = _with_embedding(random_model(), 3, 2)
    context = (np.arange(17 * 17).reshape(17, 17) % 3).astype(np.uint8)
    blob, _, _ = package.encode(z, 0.25, "learned", geo, context=context)
    (out / "refuse-context.gnc").write_bytes(blob)
    errors.append(["refuse-context", "refuse-context.gnc", "-", "context"])
    # The class raster held by the decoder rather than stored: the embedded model still needs it.
    blob, _, _ = package.encode(z, 0.25, "learned", geo, context=context, context_charged=False)
    (out / "refuse-embedding.gnc").write_bytes(blob)
    errors.append(["refuse-embedding", "refuse-embedding.gnc", "-", "class embedding"])
    (out / "errors.tsv").write_text("".join("\t".join(r) + "\n" for r in errors))
    total = sum(p.stat().st_size for p in out.iterdir() if p.is_file())
    log(f"{out}: {len(rows)} cases, {len(errors)} refusals, {total} bytes")
    return out


def _with_embedding(model: Predictor, classes: int, g: int, seed: int = 3) -> Predictor:
    rng = np.random.default_rng(seed)
    (W1, b1), *rest = model.layers
    W = np.concatenate([W1.astype(np.float32), rng.normal(0, 0.3, (W1.shape[0], g)).astype(np.float32)], 1)
    return Predictor([(W, b1)] + rest, embed=rng.normal(0, 0.5, (classes, g)))


# ---- data bundle of the codec web views ---------------------------------------------------------------------

BUNDLE_SCHEMA = "geoneural-codec-bundle-v1"
CODERS = ("sz3", "cubic-ctx", "learned")
FAMILIES = {"sz3": "conventional", "cubic-ctx": "multilevel-fixed", "learned": "learned"}
HEIGHT_QUANTUM_M = 0.01


def _file(root: Path, rel: str, raw: bytes, encoding: str, gz: bool = True) -> dict:
    data = gzip.compress(raw, compresslevel=9, mtime=0) if gz else raw
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return {"file": rel, "encoding": encoding, "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}


def error_codes(error_m: np.ndarray, scale_m: float, stride: int) -> np.ndarray:
    """Display raster of a signed error, sampled at every stride-th node: 128 + round(127 * clip(error / scale, -1,
    1)). Sampled rather than pooled, so the map shows how the error is distributed; the maximum is a metric."""
    e = np.asarray(error_m, np.float64)[::stride, ::stride]
    return (128 + np.rint(127 * np.clip(e / scale_m, -1, 1))).astype(np.uint8)


def _u16_delta(field: np.ndarray, offset: float) -> bytes:
    codes = np.rint((np.asarray(field, np.float64) - offset) / HEIGHT_QUANTUM_M)
    if codes.min() < 0 or codes.max() > 65535:
        raise ValueError("height field does not fit the uint16 range of the bundle")
    flat = codes.astype(np.uint16).ravel()
    return np.diff(flat, prepend=np.uint16(0)).astype("<u2").tobytes()


def _bits(mask: np.ndarray) -> bytes:
    return np.packbits(np.asarray(mask, bool).ravel()).tobytes()


def _model_for(region: str, models: dict | None) -> tuple[str, Predictor]:
    given = (models or {}).get(region)
    if isinstance(given, Predictor):
        return f"model-{given.sha256()[:12]}", given
    path = Path(given) if given else HOME / "results" / "v2" / "codec" / "models" / f"loro-{region}-s0.gnm"
    if not path.exists():
        raise FileNotFoundError(f"no learned model for {region} at {path}; pass models={{region: path}}")
    return path.stem, Predictor.from_bytes(path.read_bytes())


def write_web_bundle(out_dir: Path | None = None, regions=("essen-ruhr",), bounds=(0.1, 0.5),
                     models: dict | None = None, stride: int = 2, crop: int | None = None, ship_products=CODERS,
                     log=print) -> Path:
    """Products, display rasters and manifest.json of the codec views (format: web/src/codec/bundle.ts).

    For every region and bound: SZ3 (imagecodecs, in the same container), cubic-ctx and the learned coder as a
    corpus product whose model is a separate shared file. Every product is decoded from its bytes and scored
    against the reference at full resolution; the rasters are for display only. models maps a region to a
    Predictor or a .gnm path (default: the leave-one-region-out model of seed 0). crop takes a centred
    (2^k + 1)-node window instead of the whole field. ship_products: coders whose .gnc file is copied into the
    bundle (the learned one is needed for the live decode).
    """
    import time

    from geoneural.codecs import campaign, foreign
    from geoneural.common import region as region_config
    from geoneural.common import utc, write_json
    from geoneural.export.web import pool_any
    from geoneural.metrics import drainage

    out = Path(out_dir or WEB_BUNDLE)
    out.mkdir(parents=True, exist_ok=True)
    versions = foreign.versions()
    shipped_models: dict[str, dict] = {}
    region_rows = []
    for name in regions:
        z, atlas = campaign.load(name)
        spatial = package.spatial_from_atlas(atlas)
        r0 = c0 = 0
        if crop:
            ml.strides(crop)
            r0 = c0 = (z.shape[0] - crop) // 2
            z = np.ascontiguousarray(z[r0:r0 + crop, c0:c0 + crop])
            spatial = {**spatial, "west": spatial["west"] + c0 * spatial["spacing_m"],
                       "north": spatial["north"] - r0 * spatial["spacing_m"]}
        side = z.shape[0]
        sp = spatial["spacing_m"]
        routed = drainage.route(z, sp)
        ref_streams = drainage.streams(routed)
        model_id, model = _model_for(name, models)
        if model_id not in shipped_models:
            ref = _file(out, f"models/{model_id}.gnm", model.to_bytes(), "gnm", gz=False)
            shipped_models[model_id] = {"id": model_id, "file": ref, "bytes": model.nbytes(), "sha256": model.sha256(),
                                        "widths": [model.layers[0][0].shape[0], model.layers[1][0].shape[0]],
                                        "heldOut": name if model_id.startswith("loro-") else None}
        offset = float(np.floor(z.min()))
        dz = z[::stride, ::stride]
        reference = {"height": {**_file(out, f"{name}/reference.height.bin", _u16_delta(dz, offset), "u16-delta"),
                                "offsetM": offset, "quantumM": HEIGHT_QUANTUM_M},
                     "streams": _file(out, f"{name}/reference.streams.bin", _bits(pool_any(ref_streams, stride)),
                                      "bits"),
                     "minM": float(z.min()), "maxM": float(z.max()),
                     "sha256": hashlib.sha256(np.ascontiguousarray(z, "<f4").tobytes()).hexdigest()}
        products = []
        for b in bounds:
            for coder in CODERS:
                t = time.perf_counter()
                if coder == "sz3":
                    payload = foreign.encode("sz3", z, b)
                    blob = package.wrap_foreign("sz3", payload, z.shape, b, spatial)
                    breakdown = {"container": len(blob) - len(payload), "foreign": len(payload)}
                    t = time.perf_counter()
                    est = foreign.decode("sz3", package.read(blob).components["foreign"], z.shape)
                    decode_s = time.perf_counter() - t
                    lat_sha, E, standalone, mid = None, package.read(blob).E, len(blob), None
                else:
                    m = model if coder == "learned" else None
                    blob, recon, info = package.encode(z, b, coder, m, embed_model=False, spatial=spatial)
                    t = time.perf_counter()
                    est = package.decode(blob, m)
                    decode_s = time.perf_counter() - t
                    if not np.array_equal(est, recon):
                        raise RuntimeError(f"{name} {coder} {b}: decode differs from the encoder's reconstruction")
                    breakdown = dict(info["breakdown"])
                    lat_sha, E = lattice_sha256(lattice_of(est)), info["E"]
                    # The standalone file embeds the model as one more component (9 directory bytes).
                    standalone = len(blob) + (model.nbytes() + 9 if m is not None else 0)
                    mid = model_id if m is not None else None
                hm = campaign.height_metrics(z, est, b)
                sm = drainage.stream_metrics(z, est, sp, reference_routed=routed, secondary=False)
                dec_streams = drainage.streams(drainage.route(est, sp))
                stem = f"{name}/{b:g}/{coder}"
                products.append({
                    "id": f"{name}/{b:g}/{coder}", "boundM": b, "E": int(E), "coder": coder,
                    "family": FAMILIES[coder],
                    "label": {"sz3": f"SZ3 {versions.get('sz3', '').replace('sz3 ', '')}".strip(),
                              "cubic-ctx": "cubic-ctx (fixed multilevel)", "learned": "learned multilevel"}[coder],
                    "bytes": len(blob), "standaloneBytes": standalone, "breakdown": breakdown, "model": mid,
                    "metrics": {"maxM": hm["maxM"], "rmseM": hm["rmseM"], "maeM": hm["maeM"], "p99M": hm["p99M"],
                                "boundViolations": hm["boundViolations"], "streamJaccard": sm["jaccard"],
                                "streamTolerantF1": sm["tolerantF1"]},
                    "errorScaleM": b, "latticeSha256": lat_sha, "decodeS": decode_s,
                    "product": _file(out, f"{stem}.gnc", blob, "gnc", gz=False) if coder in ship_products else None,
                    "error": _file(out, f"{stem}.error.bin", error_codes(est - z, b, stride).tobytes(), "u8"),
                    "streams": _file(out, f"{stem}.streams.bin", _bits(pool_any(dec_streams, stride)), "bits"),
                })
                log(f"{stem}: {len(blob)} bytes, max {hm['maxM']:.4f} m")
        cfg = region_config(name)
        west, north = spatial["west"], spatial["north"]
        span = (side - 1) * sp
        region_rows.append({
            "id": name, "title": cfg.get("title", name), "side": side, "spacingM": sp,
            "extent": [west, north - span, west + span, north], "crs": f"EPSG:{spatial['epsg_h']}",
            "verticalCrs": f"EPSG:{spatial['epsg_v']}", "crop": {"row": r0, "col": c0} if crop else None,
            "display": {"side": (side - 1) // stride + 1, "stride": stride}, "reference": reference,
            "products": products,
        })
    manifest = {
        "schema": BUNDLE_SCHEMA, "createdUtc": utc(), "latticeM": ml.LATTICE_M, "tableId": rans.TABLE_ID,
        "streamAreaM2": drainage.STREAM_AREA_M2, "coders": list(CODERS), "bounds": [float(b) for b in bounds],
        "versions": versions, "models": list(shipped_models.values()), "regions": region_rows,
        "timing": {"qualified": False, "note": "Python decode seconds on a shared machine; indicative only"},
        "attribution": ["Terrain: DGM1, Geobasis NRW (Bezirksregierung Koeln), DL-DE-Zero-2.0"],
    }
    write_json(out / "manifest.json", manifest)
    log(f"{out}: {sum(p.stat().st_size for p in out.rglob('*') if p.is_file())} bytes")
    return out


# ---- CLI ------------------------------------------------------------------------------------------------------

def cmd_gnc_fixtures(a):
    print(write_rust_tables(a.tables))
    print(write_fixtures(a.out, a.trained))


def cmd_codec_web_bundle(a):
    print(write_web_bundle(a.out, tuple(a.regions), tuple(a.bounds), stride=a.stride, crop=a.crop))


def register(add):
    s = add("gnc-fixtures", cmd_gnc_fixtures, "Rust decoder tables and bit-exact parity fixtures (native/gnc)")
    s.add_argument("--out", type=Path, help="Fixture directory (default native/gnc/tests/fixtures)")
    s.add_argument("--tables", type=Path, help="Generated Rust tables (default native/gnc/src/tables.rs)")
    s.add_argument("--trained", type=Path, help="Trained .gnm for the Essen cases (default: leave-one-out model)")
    s = add("codec-web-bundle", cmd_codec_web_bundle, "Products, rasters and manifest of the codec web views")
    s.add_argument("--regions", nargs="+", default=["essen-ruhr"])
    s.add_argument("--bounds", nargs="+", type=float, default=[0.1, 0.5])
    s.add_argument("--stride", type=int, default=2, help="Display stride of the rasters")
    s.add_argument("--crop", type=int, help="Centred (2^k + 1)-node window instead of the whole field")
    s.add_argument("--out", type=Path, help="Bundle directory (default web/public/bundle/codec)")
