"""One candidate table for every representation that was measured on the Essen reference.

Each row is one decodable product: its bytes, its height errors on the full reference, its
stream overlap when that was measured, whether its maximum error is a guarantee or an
observation, and where the numbers come from. Charts, the browser bundle and any written
claim read this table and nothing else.

Two byte conventions exist and are never mixed on one axis:

* ``finest-per-page``: the finest lattice in independently compressed 65 x 65 pages, the
  product that matches a point-evaluating neural field. Neural rows carry their conventional
  base (if any) at the same convention.
* ``pyramid``: all five pyramid levels plus the JSON page index, as the atlas ships.

Evidence states: ``reproduced`` (regenerated by this package from the prepared reference),
``recovered`` (an earlier run of the same code; the report survives but was not rerun).
"""
from __future__ import annotations

import hashlib
from pathlib import Path

from geoneural.common import HOME, read_json

SCHEMA = "geoneural-candidates-v1"
REPORTS = {
    "tournament": "tournament-essen.json",
    "ladder": "quantised-ladder.json",
    "codec-fit": "neural-codec-fit.json",
    "drainage": "drainage-essen.json",
    "corrections": "corrections-essen.json",
    "envelope": "dense-envelope-essen.json",
    "checkpoint": "siren-checkpoint.json",
}


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def locate(name: str, root: Path | None = None) -> tuple[dict, dict] | None:
    """A report and its provenance, preferring a reproduced run over a recovered one."""
    root = Path(root or HOME / "results")
    for state in ("reproduced", "recovered"):
        path = root / state / REPORTS[name]
        if path.exists():
            return read_json(path), {"evidence": state, "report": REPORTS[name], "sha256": _sha(path)}
    return None


def _row(**fields) -> dict:
    row = {"id": None, "label": None, "family": None, "experiment": None, "package": None,
           "bytes": None, "bytesByPart": {}, "maeM": None, "rmseM": None, "maxM": None,
           "boundGuaranteed": False, "boundM": None, "streamJaccard": None, "evidence": None,
           "source": None, "notes": []}
    row.update(fields)
    return row


def from_ladder(report: dict, source: dict, jaccard_by_target: dict, conventional: bool = True) -> list[dict]:
    """Quantised neural rows and, unless the dense envelope replaces them, its conventional points."""
    rows = []
    for point in report["conventional"]["points"] if conventional else []:
        full = point["kind"] == "full-resolution-quantized"
        target = float(point["label"].split("@")[1].strip().rstrip(" m"))
        level = None if full else int(point["label"].split()[1])
        rows.append(_row(
            id=(f"q32dz-full@{target:g}" if full else f"q32dz-level{level}@{target:g}"),
            label=(f"Quantised, full resolution, {target:g} m bound" if full else
                   f"Level {level} grid ({10 * 2 ** level} m) at {target:g} m, bilinear"),
            family="conventional", experiment="quantised-ladder", package="finest-per-page",
            bytes=int(point["deployedBytes"]), bytesByPart={"pages": int(point["deployedBytes"])},
            maeM=point["maeM"], maxM=point["maxM"], boundGuaranteed=bool(point["boundGuaranteed"]),
            boundM=target if full else None,
            streamJaccard=jaccard_by_target.get(target) if full else None,
            evidence=source["evidence"], source=source))
    for entry in report["rows"]:
        for width in entry["byWidth"]:
            method = {"storage rounding": "rounded", "post-training": "ptq",
                      "quantisation-aware": "qat"}.get(width.get("method"), width.get("method"))
            tag = width["width"] if width["width"] == "float16" else f"{width['width']}-{method}"
            base = int(width.get("baseBytes") or 0)
            total = int(width["deployedBytes"])
            beaten = width.get("beatenBy")
            rows.append(_row(
                id=f"{entry['name']}/{tag}", label=f"{entry['name']}, {tag} weights",
                family="hybrid" if base else "neural", experiment="quantised-ladder",
                package="finest-per-page", bytes=total, bytesByPart={"weights": total - base, "base": base},
                maeM=width["maeM"], maxM=width["maxM"], evidence=source["evidence"], source=source,
                notes=[f"beaten by conventional {beaten['label']}"] if beaten else []))
    return rows


def from_codec_fit(report: dict, source: dict) -> list[dict]:
    """Neural codec fits with the drainage comparison, float32 and float16 storage."""
    rows = []
    for entry in report["rows"]:
        for run in entry["runs"]:
            base = int(run.get("baseBytes") or 0)
            family = "hybrid" if base else "neural"
            full = run["fullReference"]
            rows.append(_row(
                id=f"fit/{entry['name']}", label=f"{entry['name']} (codec fit, float32)", family=family,
                experiment="codec-fit", package="finest-per-page", bytes=int(run["deployedBytes"]),
                bytesByPart={"weights": int(run["deployedBytes"]) - base, "base": base},
                maeM=full["mae_m"], rmseM=full["rmse_m"], maxM=full["max_m"],
                streamJaccard=run["drainage"]["streamJaccard"], evidence=source["evidence"], source=source,
                seed=run["seed"]))
            half = run["halfPrecision"]
            rows.append(_row(
                id=f"fit/{entry['name']}/fp16", label=f"{entry['name']} (codec fit, float16)", family=family,
                experiment="codec-fit", package="finest-per-page", bytes=int(half["deployedBytes"]),
                bytesByPart={"weights": int(half["deployedBytes"]) - base, "base": base},
                maeM=half["mae_m"], maxM=half["max_m"], evidence=source["evidence"], source=source,
                seed=run["seed"], notes=["stream overlap measured on the float32 weights only"]))
    return rows


def from_corrections(report: dict, source: dict, base_row: dict | None) -> list[dict]:
    """Full-resolution quantiser plus exact corrections on a band around the reference streams."""
    rows = []
    target = float(report["targetMaxErrorM"])
    for band in report["byBandRadius"]:
        base = int(base_row["bytes"]) if base_row else None
        extra = int(band["correctionBytes"])
        rows.append(_row(
            id=f"corrected-r{band['bandRadiusCells']}@{target:g}",
            label=f"{target:g} m quantiser + exact corrections, band radius {band['bandRadiusCells']}",
            family="corrected", experiment="corrections", package="finest-per-page",
            bytes=None if base is None else base + extra,
            bytesByPart={"pages": base, "corrections": extra},
            maeM=band.get("elevationMaeM"), maxM=band["elevationMaxM"], boundGuaranteed=True, boundM=target,
            streamJaccard=band["streamJaccard"], evidence=source["evidence"], source=source,
            notes=[f"{band['protectedCells']} protected cells restored to the 0.01 m quantum"]))
    return rows


def from_envelope(report: dict, source: dict) -> list[dict]:
    """Dense conventional sweep plus the stored-mean control."""
    rows = []
    for point in report["points"]:
        level, target = point["level"], point["targetM"]
        rows.append(_row(
            id=f"q32dz-full@{target:g}" if level == 0 else f"q32dz-level{level}@{target:g}",
            label=(f"Quantised, full resolution, {target:g} m bound" if level == 0 else
                   f"{point['spacingM']:g} m grid at {target:g} m, bilinear"),
            family="conventional", experiment="dense-envelope", package="finest-per-page",
            bytes=int(point["bytes"]), bytesByPart={"pages": int(point["bytes"])}, maeM=point["maeM"],
            rmseM=point["rmseM"], maxM=point["maxM"], boundGuaranteed=bool(point["boundGuaranteed"]),
            boundM=target if level == 0 else None, streamJaccard=point.get("streamJaccard"),
            evidence=source["evidence"], source=source))
    constant = report["constantMean"]
    rows.append(_row(id="constant-mean", label="Stored field mean (one float32)", family="control",
                     experiment="dense-envelope", package="finest-per-page", bytes=constant["bytes"],
                     bytesByPart={"mean": constant["bytes"]}, maeM=constant["maeM"], rmseM=constant["rmseM"],
                     maxM=constant["maxM"], evidence=source["evidence"], source=source))
    return rows


def from_checkpoint(report: dict, source: dict) -> list[dict]:
    full = report["fullReference"]
    return [_row(id=f"checkpoint/{report['model']}",
                 label=f"SIREN {report['config']['width']}x{report['config']['depth']}, saved checkpoint",
                 family="neural", experiment="checkpoint-evaluation", package="finest-per-page",
                 bytes=int(report["deployedBytes"]), bytesByPart={"weights": int(report["weightsBytes"])},
                 maeM=full["mae_m"], rmseM=full["rmse_m"], maxM=full["max_m"],
                 streamJaccard=report["drainage"]["streamJaccard"], evidence=source["evidence"], source=source,
                 notes=[f"{report['stepsCompleted']} training steps, float32 weights"])]


def from_tournament(report: dict, source: dict) -> list[dict]:
    """Every codec in the tournament at every target, as a full pyramid package."""
    rows = []
    for result in report["results"]:
        if not result.get("available", True):
            continue
        for point in result["observations"]:
            target = point.get("target_m")
            total = point.get("total_deployment_bytes")
            payload = point.get("payload_bytes")
            at = "lossless" if target is None else f"{target:g}"
            rows.append(_row(
                id=f"pyramid/{result['codec']}@{at}",
                label=f"{result['codec']} pyramid, " + ("lossless" if target is None else f"{target:g} m bound"),
                family="conventional", experiment="tournament", package="pyramid", bytes=total,
                bytesByPart={"payload": payload, "index": None if total is None or payload is None
                             else total - payload},
                maeM=point.get("mae_m"), rmseM=point.get("rmse_m"), maxM=point.get("max_error_m"),
                boundGuaranteed=bool(result.get("error_bounded") and point.get("meets_target")),
                boundM=target if result.get("error_bounded") else None,
                evidence=source["evidence"], source=source))
    return rows


def dominated_by(row: dict, rows: list[dict], axes=("bytes", "maeM", "maxM")) -> str | None:
    """The first single row that is no worse on every axis and better on one, if any.

    Joint dominance needs one comparator row that satisfies every inequality. Two different
    rows that each win one axis do not dominate a candidate together. A missing value is
    not a zero and makes the comparison undecidable for that pair.
    """
    if any(row.get(a) is None for a in axes):
        return None
    for other in rows:
        if other is row or other["package"] != row["package"] or any(other.get(a) is None for a in axes):
            continue
        if all(other[a] <= row[a] for a in axes) and any(other[a] < row[a] for a in axes):
            return other["id"]
    return None


def best_conventional(row: dict, rows: list[dict]) -> dict | None:
    """The conventional row with the lowest mean error at no more bytes, and how the row compares.

    Dominance is a yes or no answer. This says by how much: a learned row that is undominated
    only because its maximum error is 0.1 m better while its mean error is no better has not
    earned its complexity, and the table should make that visible.
    """
    if row["bytes"] is None or row["maeM"] is None:
        return None
    pool = [r for r in rows if r["family"] == "conventional" and r["package"] == row["package"]
            and r["bytes"] is not None and r["maeM"] is not None and r["bytes"] <= row["bytes"]]
    if not pool:
        return None
    best = min(pool, key=lambda r: (r["maeM"], r["bytes"]))
    return {"id": best["id"], "bytes": best["bytes"], "maeM": best["maeM"], "maxM": best["maxM"],
            "streamJaccard": best["streamJaccard"],
            "maeGainPercent": 100.0 * (best["maeM"] - row["maeM"]) / best["maeM"],
            "maxDifferenceM": None if row["maxM"] is None or best["maxM"] is None else row["maxM"] - best["maxM"]}


def build(root: Path | None = None) -> dict:
    rows, sources = [], {}
    drainage = locate("drainage", root)
    jaccard = {}
    if drainage:
        sources["drainage"] = drainage[1]
        jaccard = {float(t["targetMaxErrorM"]): t["streamJaccard"] for t in drainage[0]["byTarget"]}
    envelope = locate("envelope", root)
    if envelope:
        sources["envelope"] = envelope[1]
        rows += from_envelope(*envelope)
    ladder = locate("ladder", root)
    crosscheck = []
    if ladder:
        sources["ladder"] = ladder[1]
        rows += from_ladder(ladder[0], ladder[1], jaccard, conventional=envelope is None)
        if envelope:
            known = {r["id"]: r for r in rows}
            for point in from_ladder(ladder[0], ladder[1], {}):
                if point["family"] != "conventional":
                    continue
                twin = known.get(point["id"])
                crosscheck.append({"id": point["id"], "ladderBytes": point["bytes"],
                                   "envelopeBytes": twin and twin["bytes"],
                                   "maeDifferenceM": twin and abs(twin["maeM"] - point["maeM"])})
    fit = locate("codec-fit", root)
    if fit:
        sources["codec-fit"] = fit[1]
        rows += from_codec_fit(fit[0], fit[1])
    corrections = locate("corrections", root)
    if corrections:
        sources["corrections"] = corrections[1]
        target = float(corrections[0]["targetMaxErrorM"])
        base = next((r for r in rows if r["id"] == f"q32dz-full@{target:g}"), None)
        rows += from_corrections(corrections[0], corrections[1], base)
    checkpoint = locate("checkpoint", root)
    if checkpoint:
        sources["checkpoint"] = checkpoint[1]
        rows += from_checkpoint(*checkpoint)
    tournament = locate("tournament", root)
    if tournament:
        sources["tournament"] = tournament[1]
        rows += from_tournament(*tournament)
    for row in rows:
        row["dominatedBy"] = dominated_by(row, rows)
        if row["family"] in ("neural", "hybrid", "corrected"):
            row["bestConventional"] = best_conventional(row, rows)
    return {"schema": SCHEMA, "region": "essen-ruhr", "sources": sources, "candidates": rows,
            "ladderCrossCheck": crosscheck,
            "conventions": {
                "finest-per-page": "Finest 1025 x 1025 lattice as independently compressed 65 x 65 pages.",
                "pyramid": "All five pyramid levels plus the JSON page index, as the atlas ships."},
            "errors": "Height errors are against the prepared 10 m reference on all 1,050,625 nodes.",
            "streams": "Stream overlap is the Jaccard index of D8 stream cells (contributing area at least "
                       "500 cells, 0.05 km2) on reference and reconstruction. A routing diagnostic, not a "
                       "hydrological simulation.",
            "dominance": "dominatedBy names one row in the same package convention that is no worse on "
                         "bytes, mean error and maximum error, and better on at least one.",
            "bestConventional": "For learned and corrected rows: the conventional row with the lowest mean "
                                "error at no more bytes. maeGainPercent > 0 means the row has the lower mean "
                                "error; maxDifferenceM > 0 means its maximum error is worse."}
