"""Sparse noisy samples: 1 % or 5 % of the 10 m nodes, with correlated observation noise.

Declared observation model: sample positions uniformly at random without replacement (fixed seed per region and
density); noise is a stationary Gaussian field with standard deviation 0.25 m and covariance
sigma^2 exp(-d^2 / (2 L^2)), L = 30 m, generated by Gaussian filtering of white noise and rescaled to that
variance. Methods receive the positions, the noisy values and the declared noise model, and nothing else.

Methods: a thin-plate (biharmonic) smoothing fit on the grid, argmin sum (z_i - d_i)^2 / sigma^2 + alpha ||L z||^2
with alpha chosen on the validation region; local universal kriging with a linear drift, the exponential
Matern 3/2 covariance fitted on training regions and the declared noise covariance added to the data
covariance (tiles of 32 x 32 targets, samples within 32 cells of the tile, at most 300); and the neural residual
model over the
thin-plate fit, reading the sample mask and the sample misfit to the fit. No coarse grid exists in this task;
the base is built from the samples alone.
"""
from __future__ import annotations

import time
from concurrent.futures import ProcessPoolExecutor

import numpy as np
import torch
from scipy import ndimage, sparse
from scipy.interpolate import griddata
from scipy.sparse import linalg as splinalg

from geoneural.recon import baselines, evaluate, fields, models, train

DENSITIES = (0.01, 0.05)
NOISE_SIGMA_M = 0.25
NOISE_LENGTH_M = 30.0
SAMPLE_SEED = 20261005
TRAIN_PATTERNS = 2
ALPHAS = (0.03, 0.3, 3.0)
SPEC = models.Features(scale_sigma=4.0, highpass_sigma=2.0, unit=1.0, floor_m=0.05, factor=None, margin=16)
CORE, BORDER, BATCH = 128, 16, 16
LR_GRID = (5e-4, 1e-3)
CHECKPOINTS = (500, 1000, 1500, 2000, 3000)
MAX_STEPS = 3000
TILE, REACH, MAX_SAMPLES = 32, 32, 300


def observe(z: np.ndarray, density: float, seed) -> tuple[np.ndarray, np.ndarray]:
    """Flat sample indices and noisy values under the declared observation model."""
    rng = np.random.default_rng(seed)
    index = np.sort(rng.choice(z.size, int(round(density * z.size)), replace=False))
    s = NOISE_LENGTH_M / np.sqrt(2.0) / fields.SPACING_M
    radius = int(np.ceil(4 * s))
    k = np.exp(-0.5 * (np.arange(-radius, radius + 1) / s) ** 2)
    k /= k.sum()
    white = rng.standard_normal(z.shape)
    noise = ndimage.correlate1d(ndimage.correlate1d(white, k, 0, mode="wrap"), k, 1, mode="wrap")
    noise *= NOISE_SIGMA_M / np.sqrt((np.outer(k, k) ** 2).sum())
    return index, z.ravel()[index] + noise.ravel()[index]


def noise_covariance(points: np.ndarray) -> np.ndarray:
    d2 = (points[:, None, 0] - points[None, :, 0]) ** 2 + (points[:, None, 1] - points[None, :, 1]) ** 2
    length = NOISE_LENGTH_M / fields.SPACING_M
    return NOISE_SIGMA_M ** 2 * np.exp(-d2 / (2 * length ** 2))


def thin_plate(shape, index, values, alpha: float, rtol: float = 1e-6, maxiter: int = 4000):
    """Grid thin-plate smoothing fit from scattered noisy samples; starts from linear interpolation."""
    rows, cols = np.unravel_index(index, shape)
    gy, gx = np.mgrid[0:shape[0], 0:shape[1]]
    start = griddata((rows, cols), values, (gy, gx), method="linear")
    near = griddata((rows, cols), values, (gy, gx), method="nearest")
    start = np.where(np.isfinite(start), start, near)
    lap = baselines._laplacian(*shape)
    weight = np.zeros(int(np.prod(shape)))
    weight[index] = 1.0 / NOISE_SIGMA_M ** 2
    system = (sparse.diags(weight) + alpha * (lap.T @ lap)).tocsr()
    rhs = np.zeros_like(weight)
    rhs[index] = values / NOISE_SIGMA_M ** 2
    count = [0]
    x, info = splinalg.cg(system, rhs, x0=start.ravel(), rtol=rtol, maxiter=maxiter,
                          callback=lambda _: count.__setitem__(0, count[0] + 1))
    return x.reshape(shape), {"alpha": alpha, "iterations": count[0], "converged": info == 0, "rtol": rtol}


def _fit_job(args):
    region, density, seed, alpha = args
    z = fields.reference(region)
    index, values = observe(z, density, seed)
    fit, report = thin_plate(z.shape, index, values, alpha)
    return region, density, seed, alpha, index, values, fit.astype(np.float32), report


def pattern_seed(region: str, density: float, pattern: int) -> list[int]:
    return [SAMPLE_SEED, int(density * 1000), pattern, sum(map(ord, region))]


def kriging(shape, index, values, model) -> tuple[np.ndarray, np.ndarray]:
    """Local universal kriging with the declared noise, tile by tile."""
    rows, cols = np.unravel_index(index, shape)
    points = np.column_stack([rows, cols]).astype(np.float64)
    mean = np.zeros(shape)
    sd = np.zeros(shape)
    order = np.argsort(rows, kind="stable")
    rs = rows[order]
    for r0 in range(0, shape[0], TILE):
        lo, hi = np.searchsorted(rs, r0 - REACH), np.searchsorted(rs, r0 + TILE + REACH)
        band = order[lo:hi]
        for c0 in range(0, shape[1], TILE):
            near = band[(cols[band] >= c0 - REACH) & (cols[band] < c0 + TILE + REACH)]
            centre = np.array([r0 + TILE / 2, c0 + TILE / 2])
            if len(near) > MAX_SAMPLES:
                d = np.hypot(points[near, 0] - centre[0], points[near, 1] - centre[1])
                near = near[np.argsort(d)[:MAX_SAMPLES]]
            ty, tx = np.mgrid[r0:min(r0 + TILE, shape[0]), c0:min(c0 + TILE, shape[1])]
            targets = np.column_stack([ty.ravel(), tx.ravel()]).astype(np.float64)
            m, v = baselines.universal_kriging(points[near] - centre, values[near], targets - centre, model,
                                               noise=noise_covariance)
            mean[ty, tx] = m.reshape(ty.shape)
            sd[ty, tx] = np.sqrt(v).reshape(ty.shape)
    return mean, sd


#: The thin-plate residual grows with distance from the nearest sample; the target is divided by
#: sigma * (1 + d / DISTANCE_SCALE) with d that distance in cells, known from the sample positions alone.
DISTANCE_SCALE = 4.0


def channels(shape, index, values, base) -> np.ndarray:
    """Sample mask, sample misfit to the base (in units of the declared noise, zero away from samples) and the
    distance to the nearest sample in cells."""
    mask = np.zeros(int(np.prod(shape)), dtype=np.float32)
    mask[index] = 1.0
    misfit = np.zeros_like(mask)
    misfit[index] = (values - base.ravel()[index]) / NOISE_SIGMA_M
    distance = ndimage.distance_transform_edt(mask.reshape(shape) == 0).astype(np.float32)
    return np.stack([mask.reshape(shape), misfit.reshape(shape), distance])


def multiplier(ex: np.ndarray) -> np.ndarray:
    return 1.0 + ex[2] / DISTANCE_SCALE


def network_extras(ex: np.ndarray) -> np.ndarray:
    return np.stack([ex[0], ex[1], ex[2] / 16.0])


class Task:
    def __init__(self, tensor, validation, device):
        self.tensor, self.device = tensor, device
        self.channels = SPEC.base_channels() + 3
        self.validation = validation
        self.size = CORE + 2 * SPEC.margin
        self.sampler = models.WindowSampler(self.size, self.size, device)
        self.weight = torch.zeros(BATCH, 1, CORE, CORE, device=device)
        self.weight[..., BORDER:-BORDER, BORDER:-BORDER] = 1.0

    def batch(self, rng):
        n, _, side, _ = self.tensor.shape
        entry = rng.integers(n, size=BATCH)
        origins = rng.integers(0, side - self.size + 1, (BATCH, 2))
        stack = self.sampler.gather(self.tensor, entry, np.tile([0, 1, 2, 3, 4], (BATCH, 1)), origins, rng)
        base, z, mask, misfit, distance = (stack[:, k:k + 1] for k in range(5))
        x, sigma = models.inputs(SPEC, base, None, torch.cat([mask, misfit, distance / 16.0], 1))
        m = SPEC.margin
        scale = sigma * (1.0 + distance[..., m:-m, m:-m] / DISTANCE_SCALE)
        return x, scale, (z - base)[..., m:-m, m:-m] / scale, self.weight

    def validate(self, model):
        maes = []
        for z, base, ex in self.validation:
            loc, _ = train.predict(model, SPEC, base, network_extras(ex), device=self.device)
            maes.append(np.abs(base + loc * multiplier(ex) - z)[8:-8, 8:-8].mean())
        return float(np.mean(maes))


def run_fold(fold, seeds, device, models_dir, frozen=None, log=print, max_steps=MAX_STEPS, checkpoints=CHECKPOINTS,
             lr_grid=LR_GRID, workers: int = 4):
    from geoneural.metrics import drainage
    start = time.perf_counter()
    validation = fold["validation"][0] if fold["validation"] else None
    failures = []
    with ProcessPoolExecutor(workers) as pool:
        if frozen:
            alpha = frozen["alpha"]
            alpha_curve = {}
        else:
            jobs = [(validation, d, pattern_seed(validation, d, 0), a) for d in DENSITIES for a in ALPHAS]
            alpha_curve = {}
            for region, density, seed, a, index, values, fit, report in pool.map(_fit_job, jobs):
                z = fields.reference(region)
                alpha_curve.setdefault(str(a), []).append(float(np.abs(fit - z)[8:-8, 8:-8].mean()))
            alpha = float(min(ALPHAS, key=lambda a: np.mean(alpha_curve[str(a)])))
        log(f"{fold['test']} sparse thin-plate alpha {alpha} curve {alpha_curve}")
        jobs = [(r, d, pattern_seed(r, d, p), alpha) for r in fold["train"] for d in DENSITIES
                for p in range(TRAIN_PATTERNS)]
        jobs += [(validation, d, pattern_seed(validation, d, 0), alpha) for d in DENSITIES] if validation else []
        jobs += [(r, d, pattern_seed(r, d, 0), alpha) for r in fold["test"] for d in DENSITIES]
        fits = list(pool.map(_fit_job, jobs))
    solver = [{"region": f[0], "density": f[1], **f[7]} for f in fits]
    failures += [{"stage": "thin-plate", **s} for s in solver if not s["converged"]]
    entries, val, test = [], [], {}
    for region, density, seed, _, index, values, fit, _ in fits:
        z = fields.reference(region)
        ex = channels(z.shape, index, values, fit)
        if region in fold["train"]:
            entries.append(np.concatenate([fit[None], z[None].astype(np.float32), ex]))
        elif region == validation:
            val.append((z, fit.astype(np.float64), ex))
        else:
            test[(region, density)] = (index, values, fit.astype(np.float64), ex)
    tensor = torch.tensor(np.stack(entries), device=device)
    task = Task(tensor, val, device)
    runs = []
    if frozen:
        recipe = dict(frozen["neural"])
    else:
        for lr in lr_grid:
            run = train.fit(task, lr=lr, steps=max_steps, checkpoints=checkpoints, seed=seeds[0], device=device)
            log(f"{fold['test']} sparse lr {lr} curve {train.curve(run)}")
            runs.append(run)
        recipe = train.select(runs)
    members = train.members(task, runs, recipe, seeds, device, bool(validation), log)
    failures += [{"variant": "neural", "seed": r["seed"], "lr": r["lr"], "reason": r["collapseReason"]}
                 for r in runs + members if r["collapsed"] or r["stalled"]]
    folder = models_dir / "-".join(fold["test"])
    folder.mkdir(parents=True, exist_ok=True)
    for k, m in enumerate(members):
        torch.save(m["model"].state_dict(), folder / f"neural-seed{k}.pt")
    del tensor, task
    model = fit_kriging(fold["train"])
    regions = {}
    for (region, density), (index, values, fit, ex) in test.items():
        t0 = time.perf_counter()
        z = fields.reference(region)
        routed = drainage.route(z, fields.SPACING_M)
        mean, sd = kriging(z.shape, index, values, model)
        rows = {"thinPlate": fit, "kriging": mean}
        locs = []
        for k, m in enumerate(members):
            loc, _ = train.predict(m["model"], SPEC, fit, network_extras(ex), device=device)
            loc = loc * multiplier(ex)
            rows[f"neural-seed{k}"] = fit + loc
            locs.append(loc)
        if len(locs) > 1:
            rows["neural-ensemble"] = fit + np.mean(locs, 0)
        inner = (slice(8, -8), slice(8, -8))
        scored = {}
        for name, est in rows.items():
            scored[name] = evaluate.heights(est[inner], z[inner])
            scored[name]["sampleMisfitRmsM"] = float(np.sqrt(np.mean((est.ravel()[index] - values) ** 2)))
            scored[name]["tileMaeM"] = evaluate.tiles(est, z)
            scored[name]["drainage"] = evaluate.streams(routed, est, fields.SPACING_M)
        from scipy.stats import norm
        levels = evaluate.quantile_levels()
        regions.setdefault(region, {"noiseFloor": evaluate.floor(z, fields.SPACING_M), "densities": {}})
        regions[region]["densities"][str(density)] = {
            "samples": int(len(index)), "methods": scored,
            "krigingIntervals": evaluate.intervals(z, {lv: mean + norm.ppf(lv) * sd for lv in levels},
                                                   fields.slope_class(z)),
            "seconds": time.perf_counter() - t0}
        log(f"{region} sparse {density}: " + ", ".join(f"{k} {v['maeM']:.3f}" for k, v in scored.items()))
    return {"fold": fold, "seeds": list(seeds), "learningRateGrid": list(lr_grid),
            "recipes": {"neural": recipe, "alpha": alpha},
            "alphaCurve": alpha_curve, "solver": solver, "kriging": model,
            "training": {"neural": train.history(runs, members)},
            "failures": failures, "regions": regions, "seconds": time.perf_counter() - start}


def fit_kriging(regions) -> dict:
    """Matern 3/2 variogram of the training regions (see `baselines`: an exponential makes a membrane fill)."""
    gamma = baselines.semivariogram([fields.reference(r) for r in regions])
    out = baselines.fit_variogram(gamma, "matern32")
    out["semivariogram"] = gamma.tolist()
    return out


NOTES = ("Task 4, sparse noisy samples (1 % and 5 % of 10 m nodes; noise 0.25 m, Gaussian covariance with 30 m "
         "length). Leave one region out over the six development regions (validation region next in the list); "
         "one sampling pattern and noise draw per test region and density. Errors over nodes 8..1016 including "
         "the sampled nodes. Neural rows are means over seeds unless named -ensemble. Paired differences are "
         "negative when the first method is better; within a region over 16 tiles, across regions over regions.")
COMPARISONS = (("neural", "thinPlate"), ("neural", "kriging"), ("kriging", "thinPlate"))


def selection_at_cap(parts) -> dict:
    """Folds whose selected step is the largest checkpoint: the rule may have been limited by the cap."""
    return {"-".join(p["fold"]["test"]): {v: r["steps"] for v, r in p["recipes"].items()
                                          if isinstance(r, dict) and r.get("steps") == max(CHECKPOINTS)}
            for p in parts}


def summarise(parts):
    per_density: dict = {}
    floors, intervals, recipes, training, failures, extra = {}, {}, {}, {}, [], {}
    for part in parts:
        key = "-".join(part["fold"]["test"])
        recipes[key] = {"fold": part["fold"], "recipes": part["recipes"], "alphaCurve": part["alphaCurve"]}
        training[key] = part["training"]
        extra[key] = {"kriging": {k: v for k, v in part["kriging"].items() if k != "semivariogram"},
                      "solver": part["solver"]}
        failures += [dict(f, fold=key) for f in part["failures"]]
        for region, result in part["regions"].items():
            floors[region] = result["noiseFloor"]
            for density, block in result["densities"].items():
                per_density.setdefault(density, {})[region] = evaluate.merge_seeds(block["methods"])
                intervals.setdefault(density, {})[region] = block["krigingIntervals"]
    tables = {d: {r: {m: evaluate.compact(row) | ({"sampleMisfitRmsM": row["sampleMisfitRmsM"]}
                                                  if "sampleMisfitRmsM" in row else {})
                      for m, row in methods.items()} for r, methods in regions.items()}
              for d, regions in per_density.items()}
    balanced = {d: {m: {k: evaluate.region_balanced({r: tables[d][r][m].get(k) for r in tables[d]})
                        for k in ("maeM", "rmseM", "p99M", "maxM")}
                    | {"tolerantF1": evaluate.region_balanced({r: tables[d][r][m]["drainage"]["tolerantF1"]
                                                               for r in tables[d]})}
                    for m in next(iter(tables[d].values()))} for d in tables}
    pairs = {d: [evaluate.paired(per_density[d], a, b) for a, b in COMPARISONS
                 if all(a in m and b in m for m in per_density[d].values())] for d in per_density}
    floor_bal = {s: {k: evaluate.region_balanced({r: f[s].get(k) for r, f in floors.items()})
                     for k in ("jaccard", "tolerantF1", "receiverAgreement", "outletAgreement")}
                 for s in ("0.01m", "0.1m")}
    return {"perRegion": tables, "regionBalanced": balanced, "paired": pairs, "noiseFloor": floors,
            "noiseFloorRegionBalanced": floor_bal, "krigingIntervals": intervals, "recipes": recipes,
            "selectionAtCap": selection_at_cap(parts), "training": training, "fitted": extra}, failures


def describe(parts):
    recipe = {"task": "sparse noisy samples", "densities": list(DENSITIES),
              "noise": {"sigmaM": NOISE_SIGMA_M, "lengthM": NOISE_LENGTH_M,
                        "covariance": "sigma^2 exp(-d^2 / (2 L^2)), Gaussian-filtered white noise rescaled"},
              "sampleSeed": SAMPLE_SEED, "trainingPatterns": TRAIN_PATTERNS,
              "thinPlate": {"alphaGrid": list(ALPHAS), "rule": "lowest validation MAE averaged over densities",
                            "solver": "conjugate gradients from linear interpolation, rtol 1e-6"},
              "kriging": {"tile": TILE, "reach": REACH, "maxSamples": MAX_SAMPLES,
                          "covariance": "Matern 3/2 variogram fitted on training regions plus the declared "
                                        "noise covariance on the data"},
              "model": {"type": "U-Net width 32 over the thin-plate fit, plus sample mask, misfit and distance "
                                "channels", "targetScale": f"local sigma * (1 + d / {DISTANCE_SCALE}), d = distance to "
                                "the nearest sample in cells",
                        "features": SPEC.record(), "window": CORE, "batch": BATCH},
              "selection": {"learningRates": {"-".join(p["fold"]["test"]): p.get("learningRateGrid", list(LR_GRID))
                                              for p in parts},
                            "checkpoints": sorted({e["step"] for p in parts for runs in p["training"].values()
                                                   for r in runs for e in r["curve"]})}}
    return recipe, {"folds": [p["fold"] for p in parts], "rule": "test region k, validation k+1, train the rest"}


def gates(results):
    from geoneural.evaluation import protocol
    out = {}
    for d in results["regionBalanced"]:
        bal = results["regionBalanced"][d]
        best = min(("thinPlate", "kriging"), key=lambda m: bal[m]["maeM"])
        pair = next(p for p in results["paired"][d] if p["comparison"] == f"neural minus {best}")
        gain = 1 - bal["neural"]["maeM"] / bal[best]["maeM"]
        out[f"neuralBeatsBest{d}"] = protocol.gate(
            "pass" if gain >= 0.02 and pair["overRegions"]["high"] < 0 else "fail",
            f"neural {bal['neural']['maeM']:.3f} m against {best} {bal[best]['maeM']:.3f} m (gain {gain:.1%})",
            minimumGain=0.02, intervalExcludesZero=True)
    return out


def frozen_recipe(parts):
    chosen = [p["recipes"]["neural"] for p in parts]
    rates = [c["lr"] for c in chosen]
    lr = min(set(rates), key=lambda r: (-rates.count(r), r))
    steps = int(np.median([c["steps"] for c in chosen]))
    alphas = [p["recipes"]["alpha"] for p in parts]
    steps = min(CHECKPOINTS, key=lambda c: (abs(c - steps), c))
    return {"task": "sparse", "recipes": {"neural": {"lr": lr, "steps": steps}, "alpha": float(np.median(alphas))},
            "fromFolds": [p["fold"] for p in parts]}
